dist: bionic
language: python
python: '3.7'
env:
- JVM_PROVIDER=openjdk JAVA_VERSION=8 DISTROS=ubuntu,debian,fedora
- JVM_PROVIDER=openjdk JAVA_VERSION=11 DISTROS=ubuntu,debian,fedora
before_install:
- openssl aes-256-cbc -K $encrypted_ab4c441ac2d2_key -iv $encrypted_ab4c441ac2d2_iv
  -in .ansible-vault-password.enc -out .ansible-vault-password -d
- sudo apt-get update -qq
install:
- pip3 install ansible pyopenssl cryptography
before_script:
- make setup ADD_ANSIBLE_PLAYBOOK_OPTS="--extra-vars host_name=ansible-java-travis-$TRAVIS_JOB_ID"
script:
- make install ADD_ANSIBLE_PLAYBOOK_OPTS="--syntax-check"
- make install
- make install 2>/dev/null | ./tests/idempotence_check.sh
after_script:
- make teardown
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
