dist: bionic
language: python
python: '3.7'
  
services:
- docker

cache: 
- pip

env:
- JVM_PROVIDER=openjdk JAVA_VERSION=8 
- JVM_PROVIDER=openjdk JAVA_VERSION=11 
# - JVM_PROVIDER=oracle JAVA_VERSION=8 
# - JVM_PROVIDER=orcale JAVA_VERSION=11 

before_install:
- openssl aes-256-cbc -K $encrypted_ab4c441ac2d2_key -iv $encrypted_ab4c441ac2d2_iv
  -in .ansible-vault-password.enc -out .ansible-vault-password -d
- sudo apt-get update -qq

install:
- pip3 install -r requirements.txt
 
script: 
- molecule --debug test
 
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
