---
language: python
python: "3.6"

env:
  - FOO=foo BAR=bar

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip3 install ansible

script:
  - "ANSIBLE_CONFIG=tests/ansible.cfg ansible-playbook -i tests/inventory tests/test.yml --syntax-check"
  - "ANSIBLE_CONFIG=tests/ansible.cfg ansible-playbook -i tests/inventory tests/test.yml"
  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ANSIBLE_CONFIG=tests/ansible.cfg ansible-playbook -i tests/inventory tests/test.yml --connection=local --become=sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence: PASS' && exit 0)
    || (echo 'Idempotence: FAIL' && exit 1)

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
