language: python
python: '3.6'
before_install:
- sudo apt-get update -qq
install:
- pip3 install ansible pyopenssl
before_script:
- openssl aes-256-cbc -K $encrypted_ab4c441ac2d2_key -iv $encrypted_ab4c441ac2d2_iv
  -in .ansible-vault-password.enc -out .ansible-vault-password -d
script:
- "ANSIBLE_CONFIG=tests/ansible.cfg ansible-playbook --vault-password-file=./.ansible-vault-password
  --inventory tests/inventory tests/test.yml --syntax-check"
- "ANSIBLE_CONFIG=tests/ansible.cfg ansible-playbook --vault-password-file=./.ansible-vault-password
  --inventory tests/inventory tests/test.yml"
- 'ANSIBLE_CONFIG=tests/ansible.cfg ansible-playbook --vault-password-file=./.ansible-vault-password
  --inventory tests/inventory tests/test.yml | grep -q ''changed=0.*failed=0'' &&
  (echo ''Idempotence: PASS'' && exit 0) || (echo ''Idempotence: FAIL'' && exit 1)'
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
