# roles/java/tasks/apply.yml
---
- include_tasks: apply-{{ jvm_provider }}.yml
  when: jvm_provider | search("oracle")

- include_tasks: apply-{{ ansible_os_family }}.yml
  when: jvm_provider | search("openjdk")

