# roles/java/tasks/apply.yml
---
- name: apply | create oracle jdk home
  file:
    path: "{{ base_home_dir }}"
    state: directory

- name: apply | unpack oracle jdk archive
  unarchive:
    src: "{{ oracle.local_archive }}"
    dest: "{{ base_home_dir }}"
    copy: no
    creates: "{{ oracle.java_home }}"

