---
dependency:
  name: galaxy
  enabled: False

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint

platforms:
  # - name: ubuntu-bionic
  #   box: ubuntu/bionic64
  # - name: debian-buster
  #   box: debian/buster64
  - name: fedora-31
    box: fedora/31-cloud-base
    box_version: "31.20191023.0"
  # - name: centos-7
  #   box: centos/7

provisioner:
  name: ansible
    
verifier:
  name: testinfra
