# roles/java/tasks/main.yml
---
- fail:
    msg: "No jvm has been selected, please set 'jvm_provider' and run playbook again."
  when: jvm_provider is not defined or ansible_os_family is not defined

- import_tasks: apply.yml
  tags:
    - apply

- import_tasks: configure.yml
  tags:
    - configure
